version: '3.9'

services:
  dhcp-server:
    build:
      context: ./dhcpd
    container_name: dhcp-server
    cap_add:
      - NET_ADMIN
    networks:
      dhcpnet:
        ipv4_address: 172.28.0.2

  dhcp-client:
    build:
      context: ./client
    container_name: dhcp-client
    depends_on:
      - dhcp-server
    cap_add:
      - NET_ADMIN
    networks:
      dhcpnet:
        ipv4_address: 172.28.0.3

networks:
  dhcpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
