version: '3.9'

services:
  dhcp-server:
    build:
      context: ./dhcpd
    container_name: dhcp-server
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - dhcp-leases:/var/lib/dhcp
    networks:
      dhcpnet:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep ':67'"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  dhcp-client:
    build:
      context: ./client
    container_name: dhcp-client
    depends_on:
      dhcp-server:
        condition: service_healthy
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      dhcpnet:
        ipv4_address: 172.28.0.3

networks:
  dhcpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"

volumes:
  dhcp-leases:
